name: Cheks

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:

jobs:

  check-changelogs:
    name: changelogs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Install dependencies
      run: sudo apt install -y fd-find

    - uses: actions/checkout@v3

    - name: git fetch
      run: git fetch origin main:main

    - name: Check changelogs
      run: ./scripts/check-changelogs.sh

